apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hermes-gateway
  namespace: argocd
spec:
  project: default
  source:
    path: hermes-gateway
    repoURL: https://github.com/fkc1e100/k3s-gitops.git
    targetRevision: HEAD
  destination:
    namespace: hermes-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
