---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: os-tuner
  namespace: kube-system
  labels:
    app: os-tuner
spec:
  selector:
    matchLabels:
      app: os-tuner
  template:
    metadata:
      labels:
        app: os-tuner
    spec:
      hostPID: true
      hostNetwork: true
      hostIPC: true
      containers:
      - name: tuner
        image: alpine:latest
        securityContext:
          privileged: true
        command: ["/bin/sh", "-c"]
        args:
        - |
          nsenter -t 1 -m -u -n -i bash -c '
          echo 10 > /proc/sys/vm/swappiness
          '
          sleep infinity
      restartPolicy: Always
