apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: os-tuner
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: os-tuner
  template:
    metadata:
      labels:
        name: os-tuner
    spec:
      hostPID: true
      containers:
      - name: tuner
        image: alpine
        command: ["/bin/sh", "-c", "echo 10 > /proc/sys/vm/swappiness && sleep infinity"]
        securityContext:
          privileged: true
