apiVersion: batch/v1
kind: Job
metadata:
  name: sre-disk-prune-rpi-3b-0d4ab0
  namespace: monitoring
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      nodeName: rpi-3b-0d4ab0
      containers:
      - name: pruner
        image: rancher/k3s:v1.28.2-k3s1
        command: ["/bin/sh", "-c", "echo 'runtime-endpoint: unix:///run/k3s/containerd/containerd.sock' > /bin/crictl.yaml && crictl rmi --prune"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: containerd-sock
          mountPath: /run/k3s/containerd/containerd.sock
      restartPolicy: Never
      volumes:
      - name: containerd-sock
        hostPath:
          path: /run/k3s/containerd/containerd.sock
          type: Socket
