apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: os-tuner
  namespace: kube-system
  labels:
    app: os-tuner
spec:
  selector:
    matchLabels:
      app: os-tuner
  template:
    metadata:
      labels:
        app: os-tuner
    spec:
      hostPID: true
      hostNetwork: true
      hostIPC: true
      priorityClassName: system-node-critical
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      containers:
      - name: tuner
        image: alpine:3.20.0
        securityContext:
          privileged: true
        command: ["/bin/sh", "-c"]
        args:
        - |
          nsenter -t 1 -m -u -n -i sh -c '
          sysctl -w vm.swappiness=10
          sysctl -w fs.inotify.max_user_watches=524288
          sysctl -w fs.inotify.max_user_instances=8192
          '
          sleep infinity
        resources:
          limits:
            cpu: 10m
            memory: 15Mi
          requests:
            cpu: 10m
            memory: 15Mi
      restartPolicy: Always
